pipeline {
	agent any

	tools {
		jdk "JDK 17"
		maven "Maven 3"
	}

	environment {
		// Git specifications
		GIT_REPO_URL    = "https://github.com/sonalkarmakar/Boardgame-Backend-Project.git"
		GIT_BRANCH_NAME = "working"

		// SonarQube specifications
		SONARQUBE_SERVER_NAME = "SonarQube Server"

		// Maven specifications
		MAVEN_GLOBAL_SETTINGS_CONFIG = "BoardGame_Backend-Global_Maven_Settings"

		// Trivy specifications
		TRIVY_FILES_DIR       = "Trivy"
		TRIVY_REPORTS_DIR     = "${env.TRIVY_FILES_DIR}/reports"
		TRIVY_TEMPLATE_URL    = "https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl"
		TRIVY_TEMPLATE_FILE   = "${env.TRIVY_FILES_DIR}/trivy-template.tpl"
		TRIVY_FS_REPORT_FILE  = "trivy-fs-report.html"
		TRIVY_FS_REPORT_NAME  = "Trivy File-system Scan Report"
		TRIVY_BLD_REPORT_FILE = "trivy-bld-report.html"
		TRIVY_BLD_REPORT_NAME = "Trivy Build Scan Report"
		TRIVY_IMG_REPORT_FILE = "trivy-img-report.html"
		TRIVY_IMG_REPORT_NAME = "Trivy Image Scan Report"

		// Docker specifications
		DOCKER_NAMESPACE  = "sonalkarmakar"
		DOCKER_REPOSITORY = "board-game-project"
		DOCKER_IMAGE_TAG  = "latest"
		DOCKER_IMAGE_NAME = "${env.DOCKER_NAMESPACE}/${env.DOCKER_REPOSITORY}:${env.DOCKER_IMAGE_TAG}"
		DOCKER_CRED_ID    = "DockerHub-Credentials"
		DOCKER_REPO_URL   = "https://index.docker.io/v1/"
		DOCKERFILE_PATH   = "Docker/Dockerfile"

		// EKS Cluster specifications
		AWS_REGION  = "ap-south-1"
		AWS_CRED_ID = "AWS-Credentials"
		EKS_CLUSTER_NAME = "BoardGame-Deployment-Cluster"

		// Email Notification specifications
		// Build Success
		PASS_MAIL_FROM  = "sender@mail.com" // Email ID of sender. Use if configured sender ID is different. REMOVE IF NOT NEEDED.
		PASS_MAIL_TO    = "abc@mail.com"
		PASS_MAIL_CC    = "efg@mail.com"
		PASS_MAIL_BCC   = "hij@mail.com"
		PASS_MAIL_REPLY = "receiver@mail.com" // Used in the field "replyTo". REMOVE IF NOT NEEDED.
		PASS_MAIL_SUBJ  = "Build SUCCESSFUL notification"
		PASS_MAIL_BODY  = "Hello, this email is to notify the successful build and deployment."
		// Build Failure
		FAIL_MAIL_FROM  = "sender@mail.com" // Email ID of sender. Use if configured sender ID is different. REMOVE IF NOT NEEDED.
		FAIL_MAIL_TO    = "xyz@mail.com"
		FAIL_MAIL_CC    = "uvw@mail.com"
		FAIL_MAIL_BCC   = "rst@mail.com"
		FAIL_MAIL_REPLY = "receiver@mail.com" // Used in the field "replyTo". REMOVE IF NOT NEEDED.
		FAIL_MAIL_SUBJ  = "Build FAILURE notification"
		FAIL_MAIL_BODY  = "Hello, this email is to notify the failure of build and deployment."
	}

	stages {
		stage('Cloning Source Code from Git Repository') {
			steps {
				checkout scmGit(
					branches: [[name: "${GIT_BRANCH_NAME}"]],
					extensions: [
						sparseCheckout(
							sparseCheckoutPaths: [
								[path: '.mvn'],
								[path: 'mvnw'],
								[path: 'mvnw.cmd'],
								[path: 'pom.xml'],
								[path: 'src'],
								[path: 'Docker'],
								[path: 'Kubernetes']
							]
						)
					],
					userRemoteConfigs: [[url: "${GIT_REPO_URL}"]]
				)
			}
		}
		stage("Compiling with Maven") {
			steps {
				sh 'mvn compile'
			}
		}
		stage("Testing with Maven") {
			steps {
				sh 'mvn test'
			}
		}
		stage("Analysing with SonarQube") {
			steps {
				withSonarQubeEnv("${SONARQUBE_SERVER_NAME}") {
					sh 'mvn verify sonar:sonar -Dsonar.projectName=BoardGame -Dsonar.projectKey=BoardGame'
				}
			}
		}
		stage("Scanning File-system with Trivy") {
			steps {
				sh '''
				mkdir -p "${TRIVY_REPORTS_DIR}"
				trivy fs --format table .
				curl -L -o "${TRIVY_TEMPLATE_FILE}" "${TRIVY_TEMPLATE_URL}"
				trivy fs . --format template --template "@${TRIVY_TEMPLATE_FILE}" -o "${TRIVY_REPORTS_DIR}/${TRIVY_FS_REPORT_FILE}"
				'''
			}
		}
		stage("Publishing Trivy Report for File-system") {
			steps {
				publishHTML([
					allowMissing:          false,
					alwaysLinkToLastBuild: true,
					keepAll:               true,
					reportDir:             "${TRIVY_REPORTS_DIR}",
					reportFiles:           "${TRIVY_FS_REPORT_FILE}",
					reportName:            "${TRIVY_FS_REPORT_NAME}",
				])
			}
		}
		stage("Packaging with Maven") {
			steps {
				sh 'mvn package'
			}
		}
		stage("Scanning Build with Trivy") {
			steps {
				sh '''
				curl -fsSL -o "${TRIVY_TEMPLATE_FILE}" "${TRIVY_TEMPLATE_URL}"
				trivy fs target/database_service_project-0.0.7-SNAPSHOT.jar --format table
				trivy fs target/database_service_project-0.0.7-SNAPSHOT.jar --format template --template "@${TRIVY_TEMPLATE_FILE}" -o "${TRIVY_REPORTS_DIR}/${TRIVY_BLD_REPORT_FILE}"
				'''
			}
		}
		stage("Publishing Trivy Report for Build") {
			steps {
				publishHTML([
					allowMissing:          false,
					alwaysLinkToLastBuild: true,
					keepAll:               true,
					reportDir:             "${TRIVY_REPORTS_DIR}",
					reportFiles:           "${TRIVY_BLD_REPORT_FILE}",
					reportName:            "${TRIVY_BLD_REPORT_NAME}",
				])
			}
		}
		stage("Deploying Artifact to Nexus") {
			steps {
				withMaven(globalMavenSettingsConfig: "${MAVEN_GLOBAL_SETTINGS_CONFIG}", traceability: true) {
					sh 'mvn clean deploy'
				}
			}
		}
		stage("Building Docker Image") {
			steps {
				withDockerRegistry(credentialsId: "${DOCKER_CRED_ID}", url: 'https://index.docker.io/v1/') {
					sh 'docker build -f "${DOCKERFILE_PATH}" -t "${DOCKER_NAMESPACE}/${DOCKER_REPOSITORY}:${DOCKER_IMAGE_TAG}" .'
				}
			}
		}
		stage("Scanning Docker Image with Trivy") {
			steps {
				sh '''
				curl -fsSL -o "${TRIVY_TEMPLATE_FILE}" "${TRIVY_TEMPLATE_URL}"
				trivy image --format table "${DOCKER_NAMESPACE}/${DOCKER_REPOSITORY}:${DOCKER_IMAGE_TAG}"
				trivy image "${DOCKER_NAMESPACE}/${DOCKER_REPOSITORY}:${DOCKER_IMAGE_TAG}" --format template --template "@${TRIVY_TEMPLATE_FILE}" -o "${TRIVY_REPORTS_DIR}/${TRIVY_IMG_REPORT_FILE}"
				'''
			}
		}
		stage("Publishing Trivy Report for Docker Image") {
			steps {
				publishHTML([
					allowMissing:          false,
					alwaysLinkToLastBuild: true,
					keepAll:               true,
					reportDir:             "${TRIVY_REPORTS_DIR}",
					reportFiles:           "${TRIVY_IMG_REPORT_FILE}",
					reportName:            "${TRIVY_IMG_REPORT_NAME}",
				])
			}
		}
		stage("Pushing Image to Docker Hub") {
			steps {
				withDockerRegistry(credentialsId: "${DOCKER_CRED_ID}", url: "${DOCKER_REPO_URL}") {
					sh 'docker push "${DOCKER_NAMESPACE}/${DOCKER_REPOSITORY}:${DOCKER_IMAGE_TAG}"'
				}
			}
		}
		stage("Deploying Application in EKS Cluster") {
			steps {
				withAWS(credentials: "${AWS_CRED_ID}", region: "${AWS_REGION}") {
					sh '''
					aws eks update-kubeconfig --region "${AWS_REGION}" --name "${EKS_CLUSTER_NAME}"
					kubectl apply -f Kubernetes/
					'''
				}
			}
		}
	}
	post {
		success {
			mail(
				from:    "${PASS_MAIL_FROM}",  // REMOVE IF NOT NEEDED
				to:      "${PASS_MAIL_TO}",
				cc:      "${PASS_MAIL_CC}",
				bcc:     "${PASS_MAIL_BCC}",
				replyTo: "${PASS_MAIL_REPLY}", // REMOVE IF NOT NEEDED
				subject: "${PASS_MAIL_SUBJ}",
				body:    "${PASS_MAIL_BODY}",
			)
		}
		failure {
			mail(
				from:    "${FAIL_MAIL_FROM}",  // REMOVE IF NOT NEEDED
				to:      "${FAIL_MAIL_TO}",
				cc:      "${FAIL_MAIL_CC}",
				bcc:     "${FAIL_MAIL_BCC}",
				replyTo: "${FAIL_MAIL_REPLY}", // REMOVE IF NOT NEEDED
				subject: "${FAIL_MAIL_SUBJ}",
				body:    "${FAIL_MAIL_BODY}",
			)
		}
	}
}