---
- name: Deploy Jenkins container
  hosts: jenkins
  vars:
    jenkins_image: jenkins/jenkins:slim
  pre_tasks:
    - name: Get host Docker group GID
      shell: "getent group docker | cut -d: -f3"
      register: docker_gid
      changed_when: false
      tags:
        - pretask1
        - jenkins
  tasks:
    - name: Run Jenkins container
      docker_container:
        name: jenkins_container
        image: "{{ jenkins_image }}"
        groups:
          - "{{ docker_gid.stdout }}"
        ports:
          - "{{ access_port }}:8080"
        volumes:
          - jenkins_home:/var/jenkins_home
          # Give Jenkins container access to host Docker
          - /var/run/docker.sock:/var/run/docker.sock
          - /usr/bin/docker:/usr/bin/docker:ro
        state: started
        restart_policy: unless-stopped
      tags:
        - task1
        - jenkins
        - docker
        - container

- name: Deploy Nexus container
  hosts: nexus
  vars:
    nexus_image: sonatype/nexus3:3.89.1-alpine
  tasks:
    - name: Run Nexus container
      docker_container:
        name: nexus_container
        image: "{{ nexus_image }}"
        ports:
          - "{{ access_port }}:8081"
          - "5000:5000"
        volumes:
          - nexus_data:/nexus-data
        state: started
        restart_policy: unless-stopped
      tags:
        - task1
        - nexus
        - docker
        - container

- name: Deploy SonarQube container
  hosts: sonarqube
  vars:
    sonarqube_image: sonarqube:community
  tasks:
    - name: Run SonarQube container
      docker_container:
        name: sonarqube_container
        image: "{{ sonarqube_image }}"
        ports:
          - "{{ access_port }}:9000"
        volumes:
          - sonarqube_data:/opt/sonarqube/data
          - sonarqube_extensions:/opt/sonarqube/extensions
          - sonarqube_logs:/opt/sonarqube/logs
        state: started
        restart_policy: unless-stopped
      tags:
        - task1
        - sonarqube
        - docker
        - container