---
- name: Install Trivy inside Jenkins container
  hosts: jenkins
  tasks:
    - name: Run Docker exec commands to install Trivy
      community.docker.docker_container_exec:
        container: jenkins_container
        user: root
        argv:
          - /bin/bash
          - -c
          - |
            apt-get update -y &&
            apt-get install -y wget gnupg &&
            wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | tee /usr/share/keyrings/trivy.gpg > /dev/null &&
            echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | tee -a /etc/apt/sources.list.d/trivy.list &&
            apt-get update -y &&
            apt-get install -y trivy

- name: Install Required Jenkins Plugins
  hosts: jenkins
  tasks:
    - name: Retrieve initial Jenkins admin password
      shell: docker exec jenkins_container cat /var/jenkins_home/secrets/initialAdminPassword
      register: jenkins_password
      changed_when: false

    - name: Install required Jenkins plugins
      community.general.jenkins_plugin:
        url: "http://{{ ansible_host }}:8080"
        url_username: admin
        url_password: "{{ jenkins_password.stdout }}"
        name: "{{ item }}"
        state: present
        with_dependencies: true
      loop:
        - aws-credentials         # AWS Credentials
        - config-file-provider    # Config File Provider
        - docker-plugin           # Docker
        - docker-workflow         # Docker Pipeline
        - adoptopenjdk            # Eclipse Temurin Installer
        - email-ext               # Email Extension
        - htmlpublisher           # HTML Publisher
        - kubernetes              # Kubernetes
        - kubernetes-cli          # Kubernetes CLI
        - maven-plugin            # Maven Integration
        - nexus-artifact-uploader # Nexus Artifact Uploader
        - pipeline-maven          # Pipeline Maven Integration
        - pipeline-aws            # Pipeline: AWS Steps
        - sonar                   # SonarQube Scanner
      register: plugin_install
      when: jenkins_password is defined

    - name: Restart Jenkins if plugins changed
      docker_container:
        name: jenkins_container
        state: started
        restart: true
      when: plugin_install.changed