---
- name: Install kubectl, AWS CLI v2, and Eksctl for managing and deploying Application Cluster
  hosts: localhost
  become: yes
  vars: # Change as needed
    kubectl_version: 1.35
    temp_storage: "/home/{{ ansible_user }}/temporary"

  pre_tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - gnupg
          - unzip
        state: present
        update_cache: yes
      tags:
        - pretask1
        - dependency

    - name: Create temporary storage directory
      ansible.builtin.file:
        path: "{{ temp_storage }}"
        state: directory

  tasks:
    - name: Add Kubernetes APT repository
      ansible.builtin.deb822_repository:
        name: kubernetes
        types: [deb]
        uris: "https://pkgs.k8s.io/core:/stable:/v{{ kubectl_version }}/deb/"
        signed_by: "https://pkgs.k8s.io/core:/stable:/v{{ kubectl_version }}/deb/Release.key"
        suites: [/]
        state: present
        enabled: yes

    - name: Update APT cache after adding repository
      ansible.builtin.apt:
        update_cache: true
      tags:
        - task6
        - kubectl
        - repository

    - name: Install kubectl
      ansible.builtin.apt:
        name: kubectl
        state: present
      tags:
        - task7
        - kubectl
        - installer

    - name: Download AWS CLI v2 compressed archive
      ansible.builtin.get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: "{{ temp_storage }}/awscliv2.zip"
      tags:
        - task8
        - awscli
        - download

    - name: Unzip AWS CLI v2 compressed archive
      ansible.builtin.unarchive:
        src: "{{ temp_storage }}/awscliv2.zip"
        dest: "{{ temp_storage }}"
        remote_src: yes
      tags:
        - task9
        - awscli
        - decompress

    - name: Run AWS CLI v2 installer
      ansible.builtin.command: "{{ temp_storage }}/aws/install"
      become: yes
      tags:
        - task10
        - awscli
        - installer

    - name: Download Eksctl compressed archive
      ansible.builtin.get_url:
        url: "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz"
        dest: "{{ temp_storage }}/eksctl_Linux_amd64.tar.gz"
      tags:
        - task11
        - eksctl
        - download

    - name: Decompress Eksctl archive
      ansible.builtin.unarchive:
        src: "{{ temp_storage }}/eksctl_Linux_amd64.tar.gz"
        dest: "{{ temp_storage }}"
        remote_src: yes
      tags:
        - task12
        - eksctl
        - decompress

    - name: Run Eksctl installer
      ansible.builtin.command: "install -m 0755 {{ temp_storage }}/eksctl /usr/local/bin"
      become: yes
      tags:
        - task13
        - eksctl
        - installer

  post_tasks:
    - name: Enable command auto-completion
      ansible.builtin.blockinfile:
        path: "/home/{{ ansible_user }}/.profile"
        state: present
        insertafter: EOF
        block: |
          # AWS CLI command completion
          complete -C "$(which aws_completer)" aws
          # Eksctl command completion
          . <(eksctl completion bash)
          # kubectl command completion
          . <(kubectl completion bash)

    - name: Remove temporary storage directory
      ansible.builtin.file:
        path: "{{ temp_storage }}"
        state: absent