---
- name: Retrieve initial Jenkins password
  hosts: jenkins
  tasks:
    - name: Read initial Jenkins admin password
      ansible.builtin.shell: docker exec jenkins_container cat /var/jenkins_home/secrets/initialAdminPassword
      register: jenkins_password
      changed_when: false
      tags:
        - task1
        - jenkins
        - input

    - name: Display Jenkins initial admin password
      ansible.builtin.debug:
        msg: "Jenkins initial admin password: {{ jenkins_password.stdout }}"
      when: jenkins_password.stdout is defined
      tags:
        - task2
        - jenkins
        - output

- name: Retrieve initial Nexus password
  hosts: nexus
  tasks:
    - name: Read initial Nexus admin password
      ansible.builtin.shell: docker exec nexus_container cat /nexus-data/admin.password
      register: nexus_password
      changed_when: false
      tags:
        - task1
        - nexus
        - input

    - name: Display Nexus initial admin password
      ansible.builtin.debug:
        msg: "Nexus initial admin password: {{ nexus_password.stdout }}"
      when: nexus_password is defined
      tags:
        - task2
        - nexus
        - output