[jenkins]
# IP_ADDRESS and JENKINS_PORT here

[kubernetes]
# IP_ADDRESS and KUBERNETES_PORT here

[monitoring]
# IP_ADDRESS, BLACKBOX_PORT, GRAFANA_PORT and PROMETHEUS_PORT here

[nexus]
# IP_ADDRESS and NEXUS_PORT here

[sonarqube]
# IP_ADDRESS and SONARQUBE_PORT here

[servers:children]
jenkins
monitoring
nexus
sonarqube

[all:vars]
ansible_user=# EC2 instance admin user
ansible_ssh_private_key_file=# Path to SSH private key