[jenkins]
3.110.153.29
[nexus]
35.154.139.108
[sonarqube]
3.111.245.94

[servers]
jenkins
nexus
sonarqube

[servers:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/ubuntu/.ssh/Ansible_SSH_key.pem