- name: Retrieve initial Jenkins password
  hosts: jenkins
  become: true
  tasks:
      - name: Read initial Jenkins admin password
      shell: docker exec jenkins_container cat /var/jenkins_home/secrets/initialAdminPassword
      register: jenkins_password
      changed_when: false

    - name: Display Jenkins initial admin password
      debug:
        msg: "Jenkins initial admin password: {{ jenkins_password.stdout }}"
      when: jenkins_password.stdout is defined

- name: Retrieve initial Jenkins password
  hosts: nexus
  become: true
  tasks:
    - name: Retrieve initial Nexus admin password
      shell: docker exec nexus_container cat /nexus-data/admin.password
      register: nexus_password
      changed_when: false

    - name: Display Nexus initial admin password
      debug:
        msg: "Nexus initial admin password: {{ nexus_password.stdout }}"
      when: nexus_password is defined
